// import {v4 as uuidv4} from 'uuid';
import type {User} from "../store/reducers/usersReducer.ts";

export const usersData: User[] = [
    {
        id: '1',
        email: 'ildar@example.ru',
        name: 'Ildar',
        username: 'Ildar',
        // hash: 'hash',
    },
    {
        id: '2',
        email: 'dilyara@example.ru',
        name: 'Dilyara',
        username: 'Dilyara',
        // hash: 'hash',
    },
    {
        id: '3',
        email: 'ilham@example.ru',
        name: 'Ilham',
        username: 'Ilham',
        // hash: 'hash',
    },
    {
        id: '4',
        email: 'polina@example.ru',
        name: 'Polina',
        username: 'Polina',
        // hash: 'hash',
    },
    {
        id: '5',
        email: 'renat@example.ru',
        name: 'Renat',
        username: 'Renat',
        // hash: 'hash',
    },
    {
        id: '6',
        email: 'elmira@example.ru',
        name: 'Elmira',
        username: 'Elmira',
        // hash: 'hash',
    },
    {
        id: '7',
        email: 'airat@example.ru',
        name: 'Airat',
        username: 'Airat',
        // hash: 'hash',
    },
    {
        id: '8',
        email: 'aigul@example.ru',
        name: 'Aigul',
        username: 'Aigul',
        // hash: 'hash',
    },
    {
        id: '9',
        email: 'radif@example.ru',
        name: 'Radif',
        username: 'Radif',
        // hash: 'hash',
    },
    {
        id: '10',
        email: 'aisely@example.ru',
        name: 'Aiselu',
        username: 'Aiselu',
        // hash: 'hash',
    },
    {
        id: '11',
        email: 'aidar@example.ru',
        name: 'Aidar',
        username: 'Aidar',
        // hash: 'hash',
    },
    {
        id: '12',
        email: 'tanselu@example.ru',
        name: 'Tanselu',
        username: 'Tanselu',
        // hash: 'hash',
    },
    {
        id: '13',
        email: 'ramis@example.ru',
        name: 'Ramis',
        username: 'Ramis',
        // hash: 'hash',
    },
    {
        id: '14',
        email: 'dinara@example.ru',
        name: 'Dinara',
        username: 'Dinara',
        // hash: 'hash',
    },
    {
        id: '15',
        email: 'ilnaz@example.ru',
        name: 'Ilnaz',
        username: 'Ilnaz',
        // hash: 'hash',
    },
    {
        id: '16',
        email: 'arina@example.ru',
        name: 'Arina',
        username: 'Arina',
        // hash: 'hash',
    },
    {
        id: '17',
        email: 'ilyas@example.ru',
        name: 'Ilyas',
        username: 'Ilyas',
        // hash: 'hash',
    },
    {
        id: '18',
        email: 'indira@example.ru',
        name: 'Indira',
        username: 'Indira',
        // hash: 'hash',
    },
    {
        id: '19',
        email: 'damir@example.ru',
        name: 'Damir',
        username: 'Damir',
        // hash: 'hash',
    },
    {
        id: '20',
        email: 'ilsiya@example.ru',
        name: 'Ilsiya',
        username: 'Ilsiya',
        // hash: 'hash',
    },
]